# .github/workflows/_templates/_node-setup.yml

name: Node Setup
description: 'Set up Node.js environment and install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
