name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build/

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo a statement
        run: echo "***** deploy step"

      - name: Echo Partially Masked AWS Credentials
        run: |
          echo "AWS Access Key ID: ${AWS_ACCESS_KEY_ID:0:4}********"
          echo "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY:0:4}********"
          echo "AWS Region: $AWS_REGION"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'your-aws-region'

  #    - name: Set up AWS credentials
  #      uses: aws-actions/configure-aws-credentials@v1
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: 'your-aws-region' # e.g., us-east-1
  #
  #    - name: Deploy to AWS
  #      run: |
  #        # Your deployment script or AWS CLI commands
  #        # Example: aws s3 sync ./build s3://your-s3-bucket-name
