name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: ./.github/workflows/_templates/_node-setup.yml

      - name: Run build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: ./.github/workflows/_templates/_node-setup.yml

      - name: Run tests
        run: npm test
